### ISSUE TITLE
addInstance, list of parent ids, problem with asSet/asSeq

### ISSUE THREAD

**Issue by dtoepel** [xmf-xmodeler/MosaicFX#105]

**Comment by MaxGertz** [comment]
Change combobox type from String to FmmlxObject -> add Converter to comboBox, send parent id's as vector to XMF

**Comment by MaxGertz** [comment]
Added in #109 
Changed type of ListView to FmmlxObject, Id's of parents Ids of the parents are sent as integer in Value[] -> XMF still throws exception

**Comment by MaxGertz** [comment]
Fixed exception in XMF, setting parents works for new metaclass & new instance #110
