### ISSUE TITLE
SetSlotValue: use "" for Strings or checkbox

### ISSUE THREAD

**Issue by dtoepel** [xmf-xmodeler/MosaicFX#106]
Now the box's content is sent to xmf and interpreted as expression to allow comples value assignments. To assingn a String, you need to use "".

To avoid confusion, the box should interpret the value as text, unless a new checkbox interpret as expression is selected. The content is then sent to xmf like now if selected, if not selected, the String is surrounded by " and sent in the same parameter.

**Comment by dtoepel** [comment]
Now the box's content is sent to xmf and interpreted as expression to allow comples value assignments. To assingn a String, you need to use "".

To avoid confusion, the box should interpret the value as text, unless a new checkbox interpret as expression is selected. The content is then sent to xmf like now if selected, if not selected, the String is surrounded by " and sent in the same parameter.

**Comment by MaxGertz** [comment]
Fixed with #138
