### ISSUE TITLE
exception panel, box too short, button does not work

### ISSUE THREAD

**Issue by dtoepel** [xmf-xmodeler/MosaicFX#118]
- [ ] lines are truncated in stack view(You can't see the end of a line in the stack trace box) #150 
 - [x] button at the bottom of the view is empty and seems broken
 - [x] exception icons print path when loaded, which it shouldn't

**Comment by dtoepel** [comment]
You can't see the end of a line in the stack trace box.

**Comment by vervallsweg** [comment]
Fixed the last two points for v1.1.8, redesign of the panel itself rescheduled for next release. Part of #150.
