### ISSUE TITLE
addAttribute Dialog

### ISSUE THREAD

**Issue by dtoepel** [xmf-xmodeler/MosaicFX#125]
level: combobox should have level 0 to class.level - 1 (now is 1 - class.level) 

check ChangeAttributeLevel as well.

Cancel button: At the moment an xmf-update is triggered even when cancel is pressed. Not necessary.

**Comment by wahidnurhani** [comment]
the requirement for level-interval is fixed.

cancel button in progress

**Comment by wahidnurhani** [comment]
bug by cancel button fixed
