### ISSUE TITLE
Dialog: Save image before quit?

### ISSUE THREAD

**Issue by mario-nolte** [xmf-xmodeler/MosaicFX#295]
Before closing the tool the user is asked "Save image before quit?" As I understood the image handling is not necessary anymore after saving the Models via XML. Can we at least hide the Image-Saving functionalities for the user (exclude it from the GUI)?

**Comment by dtoepel** [comment]
we can
somewhere in the properties i guess

**Comment by michaelbartels** [comment]
Dialog does not appear when the XModeler is closed. Saving images is still possible via the file menu.
