### ISSUE TITLE
Missing slot value > misleading error message

### ISSUE THREAD

**Issue by Fdbqp** [xmf-xmodeler/MosaicFX#3]
MetaClass::hasInstanceSlot
throws:
"is intrinsic and cannot be accessed on this level"
if slot does not exist

should:

let the user know that the slot doesn't exist

-----------------------------------------------
Original #115 from Mosaic by dtoepel

**Comment by vervallsweg** [comment]
Seems to be fixed. Correct error message displayed now. Tested in meeting on 10.10.19.
