### ISSUE TITLE
Dealing with images (system image)

### ISSUE THREAD

**Issue by MonikaKaczmarek** [xmf-xmodeler/MosaicFX#304]
A user may become quite confused: (1) there is a possibility to save an image (File menu, CC), and (2) one is asked about saving the image before the quitting. However, there is no (or at least not intuitively accessible) way to open the image. If we are not working (we are not supposed to work) with images, then why not removing this question/option when closing xmodeler?

**Comment by michaelbartels** [comment]
Already mentioned by Mario and fixed. Dialog isn't shown anymore.
