### ISSUE TITLE
A possibility to create a diagram with no name

### ISSUE THREAD

**Issue by MonikaKaczmarek** [xmf-xmodeler/MosaicFX#306]
When creating a diagram, if a name is left empty, a diagram with apparently no name is created. If one knows it, one can click on the row (without a content), and open this diagram.... I can actually have a number of no named diagrams and interact with them....  This should apparently not be the case

**Comment by dtoepel** [comment]
"Namen sind Schall und Rauch"
As such it doeas not cause any issues.
However, to avoid confusion and potential errors we could demand the name to be not empty.

**Comment by michaelbartels** [comment]
InputChecker is now implemented for the name of diagrams!
