### ISSUE TITLE
Problems with scrolling, zooming, dealing with larger diagrams

### ISSUE THREAD

**Issue by MonikaKaczmarek** [xmf-xmodeler/MosaicFX#309]
Although the new version has the nice overview panel, it seems to work correctly mostly for the concepts in the center but not for the others, depending on the zoom used, one can end up in seeing just empty diagram (Daniel witnessed that already). Navigating, or, in generally, working with larger diagrams not using a mouse is not really easy.

**Comment by dtoepel** [comment]
A minor mishap with the matrices. Those little devils are non-commutative. Should be done by now.

**Comment by dtoepel** [comment]
added moving with ALT pressed as well
