### ISSUE TITLE
Text when creating an instance is wrong

### ISSUE THREAD

**Issue by michaelbartels** [xmf-xmodeler/MosaicFX#36]
![textbox](https://user-images.githubusercontent.com/43987505/50003569-5b859280-ffa4-11e8-9ec4-bcd4945d8589.jpg)

The text should be: "Type the name of the instance:"

**Comment by vervallsweg** [comment]
Fixed in https://github.com/xmf-xmodeler/XMF/commit/3132caa9a0a5f2aa75aaf93f7374a311cc83de39
