### ISSUE TITLE
rename of a class - Name of a Class in the project-tree does not change and you can't create subclasses of that then (related to Bug #6 and #39)

### ISSUE THREAD

**Issue by michaelbartels** [xmf-xmodeler/MosaicFX#38]
When you rename an existing class, the name will change in the diagram and also in the projecttree.

But it does not change in the toolbar and you can't create a subclass of the renamed class.
When you rename the class to the origin name, you can create a subclass.

![renaming](https://user-images.githubusercontent.com/43987505/50004593-ee73fc00-ffa7-11e8-99cd-2a7df83914e7.jpg)

#6

**Comment by wahidnurhani** [comment]
fixed in commit 8da0a55918274fdfdfbe4b29b03e9f0bbac4d0c2
