### ISSUE TITLE
rename of a class in the property window throws exception

### ISSUE THREAD

**Issue by michaelbartels** [xmf-xmodeler/MosaicFX#39]
Renaming of a class in the property window throws an exception.

![name edit in properties](https://user-images.githubusercontent.com/43987505/50005626-43fdd800-ffab-11e8-84d0-4499ef80b8fc.png)

**Comment by wahidnurhani** [comment]
fixed in 3132caa9a0a5f2aa75aaf93f7374a311cc83de39

**Comment by wahidnurhani** [comment]
fixed in commit 3132caa9a0a5f2aa75aaf93f7374a311cc83de39
