### ISSUE TITLE
Boolean value editing

### ISSUE THREAD

**Issue by michaelbartels** [xmf-xmodeler/MosaicFX#47]
Instead of a string true or false to type in, you should be able to select true or false with a radio button.

![boolean](https://user-images.githubusercontent.com/43987505/52075247-1b966100-258c-11e9-8b37-95b810585a37.png)

**Comment by vervallsweg** [comment]
The old diagram client doesn't enforce datatypes, thus it will not be fixed. However this will be addressed in the new fmmlx client.
