### ISSUE TITLE
Text Editor fix right click context menu

### ISSUE THREAD

**Issue by vervallsweg** [xmf-xmodeler/MosaicFX#57]
Currently a right click opens the context menu, but closes it immediately.

**Comment by jgulden** [comment]
workaround: press Ctrl while right-clicking (tested on Linux)

**Comment by vervallsweg** [comment]
> workaround: press Ctrl while right-clicking (tested on Linux)

That workaround was apparently by design.

https://github.com/xmf-xmodeler/MosaicFX/blob/b0938891220f723cd9a606bc7b7f360d56da18c5/src/tool/clients/editors/TextEditor.java#L139

Rewritten method keeps this behavior.
