### ISSUE TITLE
Wiki erstellen

### ISSUE THREAD

**Issue by Fdbqp** [xmf-xmodeler/MosaicFX#89]
zum Wiki querverlinken

**Comment by Fdbqp** [comment]
[[Home]]

**Comment by dtoepel** [comment]
Wenn das github-wiki nichts taugt, dann über eigenes (vorhandenes!) wiki nachdenken.
https://www.wi-inf.uni-duisburg-essen.de/xmodeler-wiki/

**Comment by vervallsweg** [comment]
Im Meeting entschieden:

- [ ] uni-due media wiki wird public
- [ ] giithub wiki wird geschlossen
- [ ] github wiki introduction wird ins MosaicFX README.md kopiert

**Comment by Fdbqp** [comment]
MediaWiki ist public

ich habe die Unterseiten im GitHUB Wiki geschlossen und die Startseite leicht abgeändert, sodass dort steht, dass es ein öffentlich externes Wiki gibt. 

Ich hab eine readme.md erstellt und Pull Request gemacht.
